In [ ]:
Write sum and mean for 5 students midterm score (science, math and english)

In [43]:
sci_score = [10,20,30,40,50]
mat_score = [20,30,40,50,60]
eng_score = [30,40,50,60,70]

midterm_score = [sci_score, mat_score, eng_score]
import numpy as np

np_midterm_score = np.array(midterm_score)
print(midterm_score)
print(np_midterm_score.shape)
print(np_midterm_score[1,1])
print(np_midterm_score>40)
print(np_midterm_score[np_midterm_score>40])
print(np_midterm_score[:,0])

students_sum =np.sum (np_midterm_score, axis =0)
print(students_sum)

students_mean = np.mean(np_midterm_score, axis =0)
print(students_mean)

sci_mat_eng_score_mean =np.mean(np_midterm_score, axis =1)
print(sci_mat_eng_score_mean)
                         

[[10, 20, 30, 40, 50], [20, 30, 40, 50, 60], [30, 40, 50, 60, 70]]
(3, 5)
30
[[False False False False  True]
 [False False False  True  True]
 [False False  True  True  True]]
[50 50 60 50 60 70]
[10 20 30]
[ 60  90 120 150 180]
[ 20.  30.  40.  50.  60.]
[ 30.  40.  50.]


In [ ]:
Test

In [44]:
import numpy as np
test=np.array([[1,2,3],[4,5,6]], float)
print(test +test)
print(test.transpose())
print(test*test)
scalar =5
print (test+scalar)

[[  2.   4.   6.]
 [  8.  10.  12.]]
[[ 1.  4.]
 [ 2.  5.]
 [ 3.  6.]]
[[  1.   4.   9.]
 [ 16.  25.  36.]]
[[  6.   7.   8.]
 [  9.  10.  11.]]
